baseURL = ""
theme = "ficurinia"
title = "theBU3NO's dumb thing"
description = "my blogplace"
author = "theBU3NO"
copyright = "2023 © theBU3NO, Hugo theme licensed under <a href='https://www.gnu.org/licenses/agpl-3.0.html'>GNU AGPLv3</a> @ <a href='https://www.github.com/thebu3no/thebu3no.com'>GitHub</a>"
# TXkgTmFtZSBpcyBMZWUgUi4gQmFrZXIgYW5kIG9uIEZyaWRheSwgTm92ZW1iZXIgM3JkIGluIHRoZSB5ZWFyIDIwMDMsIEkgYW0gY29weXJpZ2h0aW5nIG15IHBlcnNvbmFsIHdlYnNpdGUgYW5kIGJsb2csIHRoZWJ1M25vLmNvbSAoZ2l0aHViLmNvbS90aGVidTNuby90aGVidTNuby5jb20pLCB1bmRlciB0aGUgcHNldWRvbnltIHRoZUJVM05PLg==
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
