baseURL = "/"
theme = "ficurinia"
title = "theBU3NO's dumb website"
description = "thebu3no's personal blog and social links"
author = "theBU3NO"
copyright = "2023 © theBU3NO, Hugo theme licensed under [GNU AGPLv3](https://www.gnu.org/licenses/agpl-3.0.html) @ [GitHub](https://www.github.com/thebu3no/thebu3no.com/tree/dev/themes/ficurinia)"
# TXkgTmFtZSBpcyBMZWUgUi4gQmFrZXIgYW5kIG9uIEZyaWRheSwgTm92ZW1iZXIgM3JkIGluIHRoZSB5ZWFyIDIwMDMsIEkgYW0gY29weXJpZ2h0aW5nIG15IHBlcnNvbmFsIHdlYnNpdGUgYW5kIGJsb2csIHRoZWJ1M25vLmNvbSAoZ2l0aHViLmNvbS90aGVidTNuby90aGVidTNuby5jb20pLCB1bmRlciB0aGUgcHNldWRvbnltIHRoZUJVM05PLg==

[params]
paginate = 3  # number of articles per page in the index
# articleSummary = false  # show a summary in article preview; default true
# summaryLength = 70  # words for article summaries, summaries have been replaced with the full post content
infiniteScrolling = false #true doesn't work idk
showTags = false  # show the Tags menu item; default true
imageInArticlePreview = true  # show images in article preview; default false
fitImageInArticlePreview = true  # make article preview images fit the article preview instead of getting cropped
showRss = false
contentWidth = "800px"  # maximum width of the site content, css syntax
paperCards = false  # enable paper card style; default false
buttonTags = false  # enable button tag style; default false
tagsInArticlePreview = true  # enable tags list in the article preview card
gridView = false  # show post list as a grid. goes well with paperCards
bigArticleTitle = true  # makes the title in the single article view bigger
navtype = "standard"  # changes the style of the pagination, available styles are: "standard", "circles"
enableShadow = false  # shows a shadow around some elements
menuStyle = "standard"  # changes the style of the main site navigation menu, available styles are: "standard", "buttons"
inputStyle = "standard" # changes the style of inputs (like the searchbar), available styles are: "standard", "buttons"
enableSearch = true  # enable search page
searchbarEverywhere = true  # if the searchbar should be shown in every page; requires enableSearch
searchMenuLink = false  # add a search link to the navigation menu; requires enableSearch
mobileHamburgerNav = false  # alternative hamburger menu layout for the main nav menu when screen is small
tocBeforeImage = false  # show the table of contents before the main article image; default false


[menu]

[[menu.icons]]
  identifier = "email"
  name = "send me an e-mail - howdy.partner436@slmail.me - yes that's really the address"
  url = "mailto:howdy.partner436@slmail.me"
  weight = 1

[[menu.icons]]
  identifier = "twitter"
  name = "twitter.com/theBU3NO"
  url = "https://twitter.com/thebu3no"
  weight = 2

[[menu.icons]]
  identifier = "youtube"
  name = "youtube.com/@theBU3NO"
  url = "https://youtube.com/@thebu3no"
  weight = 3

[[menu.icons]]
  identifier = "discord"
  name = "Discord Username: theBU3NO"
  url = ""
  weight = 4

[[menu.icons]]
  identifier = "steam"
  name = "steamcommunity.com/id/theBU3NO"
  url = "https://steamcommunity.com/id/thebu3no"
  weight = 5


